-- Autonomy Regulation Atlas
-- Schema v1.0 — expand phase
--
-- IMPORTANT:
-- This migration only expands the existing schema.
-- It does not remove or rename the old columns/tables used by the current frontend.

-- ============================================================
-- 1. ORGANIZATIONS / ISSUERS
-- ============================================================

create table if not exists public.organizations (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null,
  slug text,
  organization_type text,
  website_url text,
  unique (name)
);

alter table public.organizations enable row level security;


-- ============================================================
-- 2. DEPLOYMENT / REGULATORY GATES
-- ============================================================

create table if not exists public.deployment_stages (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null,
  slug text not null unique,
  description text,
  sort_order integer
);

alter table public.deployment_stages enable row level security;

insert into public.deployment_stages
  (name, slug, description, sort_order)
values
  (
    'Product compliance',
    'product_compliance',
    'Applicable technical, safety and product-level compliance requirements.',
    10
  ),
  (
    'Testing and assessment',
    'testing_assessment',
    'Testing, technical assessment and evidence required before an approval or authorization decision.',
    20
  ),
  (
    'Vehicle / system approval',
    'vehicle_approval',
    'Type approval, certification, self-certification or another product-approval mechanism.',
    30
  ),
  (
    'Market access',
    'market_access',
    'Legal ability to place or make the compliant product available on the relevant market.',
    40
  ),
  (
    'Road-use authorization',
    'road_use_authorization',
    'Authorization allowing automated or driverless operation on public roads.',
    50
  ),
  (
    'Operational-area authorization',
    'operational_area_authorization',
    'Approval of a defined operating area, route or other geographically limited operating domain.',
    60
  ),
  (
    'Vehicle registration',
    'registration',
    'Registration or admission of the individual vehicle to road traffic.',
    70
  ),
  (
    'Commercial operation',
    'commercial_operation',
    'Sector-specific permission to provide passenger, freight or another commercial transport service.',
    80
  ),
  (
    'In-use monitoring',
    'in_use_monitoring',
    'Ongoing monitoring, reporting and compliance obligations during operation.',
    90
  ),
  (
    'Post-market',
    'post_market',
    'Post-market surveillance, conformity of production, recalls and related obligations.',
    100
  )
on conflict (slug) do nothing;


-- ============================================================
-- 3. EXPAND JURISDICTIONS
-- ============================================================

alter table public.jurisdictions
  add column if not exists jurisdiction_type text;

-- Existing Netherlands row remains untouched.
-- Later examples:
-- EU          -> supranational
-- Netherlands -> national
-- Germany     -> national
-- California  -> subnational


-- ============================================================
-- 4. EXPAND CLAIMS
-- ============================================================

alter table public.claims
  add column if not exists source_proposition text,
  add column if not exists atlas_interpretation text,
  add column if not exists applicability_note text,
  add column if not exists research_status text not null default 'needs_verification',
  add column if not exists valid_from date,
  add column if not exists valid_to date,
  add column if not exists published boolean not null default false;


-- ============================================================
-- 5. CLAIM ↔ JURISDICTION
-- ============================================================

create table if not exists public.claim_jurisdictions (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  claim_id bigint not null
    references public.claims(id)
    on delete cascade,
  jurisdiction_id bigint not null
    references public.jurisdictions(id)
    on delete cascade,
  unique (claim_id, jurisdiction_id)
);

create index if not exists claim_jurisdictions_claim_id_idx
  on public.claim_jurisdictions(claim_id);

create index if not exists claim_jurisdictions_jurisdiction_id_idx
  on public.claim_jurisdictions(jurisdiction_id);

alter table public.claim_jurisdictions enable row level security;

-- Lossless migration of the relationships we already created manually.
insert into public.claim_jurisdictions (claim_id, jurisdiction_id)
select id, jurisdiction_id
from public.claims
where jurisdiction_id is not null
on conflict (claim_id, jurisdiction_id) do nothing;


-- ============================================================
-- 6. CLAIM ↔ REGULATORY GATE
-- ============================================================

create table if not exists public.claim_stages (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  claim_id bigint not null
    references public.claims(id)
    on delete cascade,
  deployment_stage_id bigint not null
    references public.deployment_stages(id)
    on delete cascade,
  unique (claim_id, deployment_stage_id)
);

create index if not exists claim_stages_claim_id_idx
  on public.claim_stages(claim_id);

create index if not exists claim_stages_stage_id_idx
  on public.claim_stages(deployment_stage_id);

alter table public.claim_stages enable row level security;


-- ============================================================
-- 7. EXPAND SOURCES
--
-- We deliberately keep the table name "sources" for now.
-- The current frontend still reads it.
-- Later, after the frontend refactor, it may become "documents".
-- ============================================================

alter table public.sources
  add column if not exists organization_id bigint
    references public.organizations(id)
    on delete set null,
  add column if not exists geographic_level text,
  add column if not exists instrument_type text,
  add column if not exists binding_status text,
  add column if not exists applicability_mechanism text;


-- ============================================================
-- 8. MIGRATE EXISTING AUTHORITY DATA
-- ============================================================

insert into public.organizations (name)
select distinct trim(authority)
from public.sources
where authority is not null
  and trim(authority) <> ''
on conflict (name) do nothing;

update public.sources s
set organization_id = o.id
from public.organizations o
where s.organization_id is null
  and s.authority is not null
  and trim(s.authority) = o.name;


-- Existing source_type is preserved.
-- Copy it to the new instrument_type field as an initial value.
update public.sources
set instrument_type = source_type
where instrument_type is null
  and source_type is not null;


-- ============================================================
-- 9. HELPFUL INDEXES
-- ============================================================

create index if not exists sources_organization_id_idx
  on public.sources(organization_id);

create index if not exists claims_research_status_idx
  on public.claims(research_status);

create index if not exists claims_published_idx
  on public.claims(published);